### ISSUE TITLE
BE > Edit Post > ClassifAI > disabled, Automatically tag content on update > Click on "Suggest terms and tags." button getting an error message

### ISSUE THREAD

**Issue by QAharshalkadu** [10up/classifai#665] opened 2024-01-24 12:25 UTC
### Describe the bug

BE > Edit Post > ClassifAI > disabled, Automatically tag content on update > Click on "Suggest terms and tags."
button getting an Error: Taxonomy not found. Double-check your settings.

### Steps to Reproduce

1. BE > Edit Post > ClassifAI 
2. Disabled, Automatically tag content on update
3. Click on Suggest terms and tags
button 
4. Observe

### Screenshots, screen recording, code snippet

https://prnt.sc/6uYKFsXhCjao

### Environment information

Local

### WordPress information

Wordpress 6.4.2 , PHP 6.4.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment] 2024-02-05 23:15
I think this is working correctly now after the changes made in #611 (or at least I can't reproduce this problem now). Going to close this out but if anyone else can reproduce, feel free to re-open.

**Closed as completed by dkotter** 2024-02-05 23:15 UTC
