### ISSUE TITLE
Update release process to attach ZIP archive to GH release

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#412] opened 2023-03-16 19:31 UTC
### Is your enhancement related to a problem? Please describe.

If we can tweak the release process to attach a ZIP archive to the GitHub releases (like Distributor does), then we can start to get _some_ stats on ZIP downloads and a little sense of usage of ClassifAI.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ravinderk** [comment] 2023-05-24 15:01
@dkotter I tested the existing workflow on the forked repo and it is working fine: https://github.com/ravinderk/classifai/releases/tag/2

I find out that the release action does not trigger [this workflow](https://github.com/10up/classifai/blob/develop/.github/workflows/build-release-zip.yml). Can you check this?

**Comment by dkotter** [comment] 2023-05-24 20:23
Hmm.. this is weird. Not sure why it would work on your forked repo but not here. It also is basically the same as what we have on [Distributor](https://github.com/10up/distributor/blob/develop/.github/workflows/release.yml) and that's been working fine.

It seems this was added in #390 to close out #367 (which looks like this issue is a duplicate of that one). @iamdharmesh worked on that PR, curious if you have any thoughts Dharmesh on why this isn't being triggered?

I would at least expect to see some runs for this within the [Actions tab](https://github.com/10up/classifai/actions/workflows/release.yml) but the only ones in there are the ones we manually triggered. So it seems this is never being triggered on the release event but not sure why.

**Comment by ravinderk** [comment] 2023-07-17 06:39
> Hmm.. this is weird. Not sure why it would work on your forked repo but not here. It also is basically the same as what we have on [Distributor](https://github.com/10up/distributor/blob/develop/.github/workflows/release.yml) and that's been working fine.
> 
> It seems this was added in #390 to close out #367 (which looks like this issue is a duplicate of that one). @iamdharmesh worked on that PR, curious if you have any thoughts Dharmesh on why this isn't being triggered?
> 
> I would at least expect to see some runs for this within the [Actions tab](https://github.com/10up/classifai/actions/workflows/release.yml) but the only ones in there are the ones we manually triggered. So it seems this is never being triggered on the release event but not sure why.

@dkotter Can you compare `Actions` settings with `distributor`? This is possible that both plugins have different `Actions` configurations, preventing action from triggering on the release Github event.

[Release workflow triggers correctly](https://github.com/ravinderk/classifai/releases/tag/2) on the forked repository.

Because of this repository access limitation, I can debug in a limited context. Can you take over this issue if the above suggestion does not resolve it?

cc: @iamdharmesh

**Comment by dkotter** [comment] 2023-07-18 20:05
Settings look the same as far as I can tell but I've gone ahead and changed our `Build release zip` workflow to match exactly what Distributor does to see if that works any better. I'll test that out in our next release

**Closed as completed** 2023-08-14 14:16 UTC
Labels: help wanted
