### ISSUE TITLE
Setup Cypress for E2E testing

### ISSUE THREAD

**Issue by vikrampm1** [10up/classifai#337] opened 2022-04-20 12:24 UTC
**Is your enhancement related to a problem? Please describe.**

See overall concept in the [OSBP guide](https://10up.github.io/Open-Source-Best-Practices/testing/#e2e-testing) and example setups on [Simple Podcasting](https://github.com/10up/simple-podcasting), [Restricted Site Access](https://github.com/10up/restricted-site-access), and https://github.com/10up/ElasticPress/pull/2446.

**Describe the solution you'd like**

- [ ]   add base GitHub Action
- [ ]   add .wp-env.json
- [ ]   add base docker files
- [ ]   update package.json / package lock files
- [ ]   add cypress tests
- [ ]   remove any WP Acceptance components

**Designs**

n/a

**Describe alternatives you've considered**

n/a

**Additional context**

https://github.com/10up/cypress-wp-setup/ && https://github.com/10up/cypress-wp-utils will be helpful in getting this spun up and some initial test commands to leverage.

**Comment by dkotter** [comment] 2022-04-21 20:24
Looks like this may be a duplicate of #333

**Closed as completed** 2022-04-22 02:45 UTC
Labels: needs:engineering
